---
sudo: false
language: python
matrix:
  fast_finish: true
  include:
    - python: "3.5.3"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
install: "make init"
script: "make ci"
cache:
  directories:
    - $HOME/.cache/pip
jobs:
  include:
    - stage: "coverage"
      python: "3.6"
      script: "pipenv run codecov"
